# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: efe4be128429ee1c5b30b4987ea7ceb02e99bdffd89267115312bcf621c2194da7c7e380095046335d1ae4cec916cdd99d91a9097cf25628f960900b1650e8c4

test:
  secret_key_base: 05343b62ec76f2e4aa72f76f88f3fbfbcb90987b7d24cfa16bbca419cbd8df0aac7ff7571d4147809ec2a365e40f906450c5b9ca447a12edaefd9ea95a69ebf8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
